### PR TITLE
Enabled active toggle in editor

### PR DESCRIPTION
**Pull request by DefiantZombie**
Generic health module excluded

### CODE REVIEW

**Comment by DefiantZombie** [comment]
Discovered this causes a bug with certain module types. I failed to notice that the Health Module title can indicate more than just the generic space type.

Looking for a solution now, but I will close this PR if I can't find a solution.

**Comment by GarwelGarwel** [comment]
What is `!Mathf.Approximately(multiplier, 1.0f)` used for?

**Comment by DefiantZombie** [comment]
It's a utility method for Unity that checks if a value is close enough to another to count as that value. Avoids any floating point errors.

**Comment by GarwelGarwel** [comment]
I understand that, but why do you need to check it?

**Comment by DefiantZombie** [comment]
Ah! Because if guiActiveEditor is set to true without some sort of check, then health modules that shouldn't be disabled show up on the action menu. I.e. Living spaces, radiation shielding, etc.

**Comment by DefiantZombie** [comment]
Or... I'm a big dumb dumb. I sincerely apologize. I'm working on adding action group items and just now saw that this is the job of IsAlwaysActive. Let me fix and test the change again.

**Comment by DefiantZombie** [comment]
Okay that should fix it. I've got action groups working as well, but after screwing up this simple PR I think I'll have them tested by someone other than me before I risk ruin your beautifully written mod.

**Comment by GarwelGarwel** [comment]
It's ok. My code is barely documented, so I'm surprised you sorted it out by yourself. Will test your commit.

**Pull request merged**
